name: Deploy HTTP Server

on:
  push:
    branches:
      - main
    paths:
      - "httpServer/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      VERSION: ${{ github.sha }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      #
      # Installs Node.js
      #
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      #
      # Installs dependencies.
      #
      - name: Install dependencies
        run: npm install
        working-directory: ./httpServer

      #
      # Run unit tests
      #
      - name: Unit tests
        run: npm run test
        working-directory: ./httpServer
